logo_title: tekzv

favicon: /favicon.ico

menu:
  About Me: /about
  Kindle: https://www.notion.so/kghazb/1e4012e19ac7475099c6730c1771a775?v=7f4a8ba1b66f4ecf91d04ae3fb267d27
  Github: https://github.com/tinyRatP

valine:
  enable: false
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false